### ISSUE TITLE
Is there a way to do level range filter of RollingFile (Log4j2) similarly  in aws appender? 

### ISSUE THREAD

**Issue by sikamedia** [kdgregory/log4j-aws-appenders#103]
It would be nice to have level ranger filter (log4j2 LevelRangeFilter similar ) to separate different logs in different log groups, but under a same package.

**Comment by sikamedia** [comment]
Thanks for the hinds. It possible to use the similar kinda of filter for CloudWatch Appender? However, I have not tried ThresholdFilter in CloudWatch Appender.  Just want to make sure the approach.

**Comment by kdgregory** [comment]
@sikamedia - yes. These appenders behave just like the built-in appenders.
