### ISSUE TITLE
Can this appender write logs when used in EMR spark jobs?

### ISSUE THREAD

**Issue by rohitaila** [kdgregory/log4j-aws-appenders#106]
When i tried using this appender in EMR spark job, i got an exception saying 
log4j:ERROR Could not instantiate class [com.kdgregory.log4j.aws.KinesisAppender].
java.lang.ClassNotFoundException: com.kdgregory.log4j.aws.KinesisAppender

inspite of including this dependency in my fat jar as well as adding a package in the spark-submit command.

**Comment by kdgregory** [comment]
@rohitaila - sorry, not familiar with the specifics of packaging for EMR.

The only thing that I can think of that would cause this, other than the appenders JAR not being on the classpath, is that the appender depends on a second JAR, `com.kdgregory.logging:aws-shared`. If you're using a build tool such as Maven, however, that second JAR will be automatically added to the project dependencies. But it's worth checking that that JAR is indeed part of the deployment bundle.

The only other suggestion is to make sure that you're using the correct variant of this library for the logging framework that you're using. In other words, verify that your build command isn't using the Log4J 2.x version with a Log4J 1.x logger, or vice-versa.

**Comment by jinamshah** [comment]
@rohitaila try changing `/etc/spark/conf.dist/log4j.properties` file. Apparently, unless the cloudwatch appender is created in the default log4j properties, it will not work in your custom log4j properties.
I tried this for pyspark application being submitted through `spark-submit` command.
Let me know if you have any other questions

**Comment by JustAnotherContributor** [comment]
Hi @rohitaila, did you end up resolving this issue? I'm having the same problem and logged another issue about it, #163, before realising there was another, much older, ticket already logged.
