### ISSUE TITLE
Where can we configure AWS credentials?   

### ISSUE THREAD

**Issue by ChetanParekhWW** [kdgregory/log4j-aws-appenders#111]
We are evaluating these appenders to use in our solution where we are hosting applications outside AWS and need to send logs to AWS CloudWatch. Where can we configure AWS credentials?

**Comment by kdgregory** [comment]
@ChetanParekhWW - The AWS Java SDK provides several mechanisms for providing credentials, as [documented here](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html).

I personally prefer environment variables, which are also the preferred mechanism for the ["twelve factor" app](https://12factor.net/).
