### ISSUE TITLE
Support AWS Java SDK v2

### ISSUE THREAD

**Issue by kdgregory** [kdgregory/log4j-aws-appenders#118]
The v2 SDK represents a complete rewrite, with different package names. Attempting to use this library in an app that uses the v2 libraries results in `NoClassDefFoundError`.

Implementing this change will require rewriting the `aws-shared` module. It will also require all users of the library to explicitly include the variant of that module that they want to use (although I could default to the v1 variant). It also means an additional set of integration tests, with facade methods so that I'm not duplicating test logic.

To date, it hasn't seemed worth the effort: at the time this library was written, the v2 SDK only supported a few services, and AWS was committed to supporting the v1 SDK. I have to assume, however, that new applications will depend on the v2 SDK because it provides easier usage than v1.

Until this is implemented, the work-around is to _also_ include the v1 JARs.

**Comment by bvanderveen** [comment]
With AWS SDK 2.x having been out for at least a couple years now, the readme for this project probably deserves a large, obvious callout at the top that only the 1.x SDK is supported.

**Comment by kdgregory** [comment]
This has now been implemented but not yet released. Anyone is welcome to try out the snapshot build in trunk.

**Comment by kdgregory** [comment]
Released.

**Comment by bvanderveen** [comment]
Sweet! We are tracking this on our internal JIRA and will get to it in the next couple months.
