### ISSUE TITLE
Catching Exceptions

### ISSUE THREAD

**Issue by jenn-zapata** [kdgregory/log4j-aws-appenders#125]
I have a question. I want to use this appender to send logs to CloudWatch. The only issue I have is that our application is required to shutdown when logging fails. Initially, I tried to wrap this appender in a custom Failover Appender that shuts down the app when logging fails. Is there anyway to "throw" the exceptions that are internally handled by the CloudWatch Appender so I can handle them at the application level or configure a custom error handler? From what I can tell, the ignoreExceptions attribute is not available. Thanks!

**Comment by kdgregory** [comment]
@jenn-zapata - Making this work in a configurable way would involve a large number of changes at a fairly deep level, so is not something that I'd be willing to add to the library. If you want to fork, however, here is how I would approach it as a one-off solution:

The basic problem is that this library batches messages and sends them on a background thread. So you'll need to disable this background thread, as well as the batching logic. This will _dramatically_ decrease performance: it takes about 50 ms to write a single message to CloudWatch Logs, and you'll be paying this for every message.

The place to make this change is the [AbstractLogWriter](https://github.com/kdgregory/log4j-aws-appenders/blob/trunk/aws-shared/src/main/java/com/kdgregory/logging/aws/internal/AbstractLogWriter.java) class, which is in the `aws-shared` module. You'll need to change the `addMessage()` method to create a list of messages and then call `sendBatch()` directly. This will leave the background thread running, but not doing anything.

**Important:** you'll also need to make `addMessage()` synchronized.

Good luck if you choose to do this, but I really think it's the wrong thing to do. Instead, I recommend using one of the standard file-based appenders, along with the AWS logs agent to write to CloudWatch.
