### ISSUE TITLE
How do we reach firehose delivery stream ?

### ISSUE THREAD

**Issue by SachJbp** [kdgregory/log4j-aws-appenders#146]
I am using the below in log4j.properties:
```
log4j.appender.kinesis=com.kdgregory.log4j.aws.KinesisAppender
log4j.appender.kinesis.streamName=stream_name
log4j.appender.kinesis.layout=com.kdgregory.log4j.aws.JsonLayout
```
What change should be made to access the firehose delivery stream?

**Comment by kdgregory** [comment]
The Kinesis appender only writes to a Kinesis Stream. If you want to use Firehose, you should configure it to accept input from the stream (which is a good practice anyway, given that you can scale Kinesis streams more easily than a Firehose).
