### ISSUE TITLE
Issue with AWS SDK2.x

### ISSUE THREAD

**Issue by psangyam** [kdgregory/log4j-aws-appenders#147]
We are using kdgregory API to send the logs to AWS cloudwatch. We have voice call application ,during the call initilization and running, the generated logs we send it to AWS cloudwatch. When we upgrade to SDK2.x, application call is not getting started due to delay in log4j initilization. On second time, we are able to run our application. 
Following SDK2.0 API jars we are using
AWS SDK2.0-2.17.35
aws-facade-v2-3.0.1
log4j-1.2.17
reactive-streams-1.0.3
log4j1-aws-appenders-1.0.3
We did not see the delay in log4j initialization in SDK1.0. Working as expected.
aws-java-sdk-core-1.11.495.jar
aws-java-sdk-logs-1.11.495.jar
aws-shared-2.4.0.jar
log4j1-aws-appenders-2.4.0.jar
log4j-1.2.17
We see there is lot of changes in the code and its package structure has been changed  among SDK1.0 and SDK2.0.
How can we avoid log4j inistialization with AWS SDK2.0. We tried the log4j options like batchDelay..., but no use.

**Comment by kdgregory** [comment]
@psangyam 

First off, you're not actually using the appenders library with the AWS 2.0 SDK. You are using version 2.4 of the library, which only works with SDK 1.x (and you're including 1.11.495 jars to make it work). You will need to update to appenders version 3.0.1 to use SDK version 2.0 (adding in the facade jar alone, as you've done here, is not sufficient).

It's possible that there's some conflict between the AWS 2.17.35 and 1.11.495 JARs, but I doubt that: other people have used mixed JARs without an issue. But once you upgrade the appenders to 3.0.1 you should be able to get rid of those 1.11.495 jars.

The appender itself should not slow anything down: Log4J 1.x appenders are initialized asynchronously, and do not block the main thread. However, the appenders use a background thread to write messages, and introduce a delay between the time that your application writes log entries and they appear in the logsThis delay is configurable; the default is (I believe) 2 seconds.

I recommend following the instructions in the [troubleshooting guide](https://github.com/kdgregory/log4j-aws-appenders/blob/trunk/docs/troubleshooting.md) to see exactly what's happening with the appenders library vis-a-vis your application.
