### ISSUE TITLE
Appender initialization in a Spring Boot environment with access/secret keys

### ISSUE THREAD

**Issue by roded** [kdgregory/log4j-aws-appenders#164]
Hi,
I'm trying to initialize the `CloudWatchAppender`'s `CloudWatchLogsClient` in a Spring Boot environment using access and secret keys and an assumed role.

Ideally, I'd like to use the application's property source for these keys instead of exposing them as statically available environment variables.
I understand this this is not possible in the `clientFactory` static method since in a Spring Boot application, the Logback context is loaded before the application's.

If exposed via `CloudWatchAppender` setters, the access and secret keys could be injected into the appender using Spring's `springProperty` extensions.

Would a PR to add access/secret keys to the appender be accepted?
Am I missing another, more obvious, solution?

Much obliged.

**Comment by kdgregory** [comment]
Sorry, but this is not something I'm willing to accept. Adding configuration properties for access/secret keys is in my opinion a security hole, because those keys will be stored _somewhere_, most likely in a configuration file that's checked into source control.

AWS gives you multiple options for providing security tokens. For development, you can either use environment variables or a configuration file in `$HOME/.aws`.

For deployment, you should be using a role attached to your execution environment. For EC2 this is the instance profile; for Lambda it's the execution role, and for ECS it's the task role (_not_ task execution role). These mechanisms work transparently with the AWS SDK, and provide credentials that have a limited lifetime and can be restricted to exactly the permissions needed.

**Comment by roded** [comment]
I agree with your security risk assessment. 

However, there are cases in which this appender can be useful in an application running in an on-premise environment interacting with AWS services. For such cases, instance profiles, execution roles and task roles are not applicable. As far as I know, access/secret keys are the only possible solution.

**Comment by kdgregory** [comment]
It's true that on-prem deployments limit your options. There are, however, still a couple of things that you can do to implement securely:

1. Use `$HOME/.aws` to store credentials. In my opinion this is the most secure choice, but limits your ability to run multiple applications on the same infrastructure. You can use a separate user for each application (not a bad idea in general; it's what Android does), but that will increase the complexity of your deployments.

2. Use environment variables that identify a long-lived user, but require all clients to assume a role to actually do anything. The appenders already support assumed roles (although only for the appenders themselves -- things like retrieving substitution values from Parameter Store aren't supported). But it means that your Spring code will have to do the same. The one big benefit of this is that you can add conditions to the role's trust policy, to ensure that you're only assuming the role from inside your data center / lan.

3. Read the Spring properties from within the static client factory. I don't know how you're deploying, but either the access keys are available as a properties/XML file within the deployment bundle, or they're available somewhere on the filesystem.

There is a fourth option: if you feel that adding setters for access and secret keys are the best option, then you are of course free to fork the codebase and add them; I believe that several of the existing forks are for exactly that reason. It should be less than a day's work: add the properties to `AbstractWriterConfig`, setters to whichever appender you use, and then attach a `StaticCredentialProvider` (or whatever it's named) in `ClientFactory.create()` (a PR, by comparison, would need to do that for all of the appenders, in all of the logging frameworks, and have tests that verify behavior).

If you're concerned about maintaining this fork with my upstream changes, don't be: as far as I'm concerned, this library is "done" and won't be receiving any major updates. Of course, AWS may decide to release a "version 3" SDK ...

My one request is that you change the artifact name to something like `patched-log4j-aws-appenders`, to make it clear to anyone who comes after you that it isn't the original library.

**Comment by roded** [comment]
I am indeed using keys and assuming a role which was what brought me to your library, since it's the only CloudWatch Logback appender I've been able to find which does currently support assumeRole functionality.

Reading the Spring properties from the static client factory is indeed a valid solution, a bit hacky but I can live with it.

However, since I'd like to make some additional changes to the appender (a runtime flag to disable the appender, lazy log stream creation, allow disabling log group creation) , I'll fork your project and rename the artifact as you requested.

Thanks for the reply @kdgregory.
