### ISSUE TITLE
IAM roles for service accounts

### ISSUE THREAD

**Issue by ladyginan** [kdgregory/log4j-aws-appenders#165]
Hi, 

Is it possible to use IRSA for cloudwatch client authentication?
https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html

**Comment by kdgregory** [comment]
I have never used that, but based on the documentation I would expect it to work:

> IAM roles for service accounts provide the ability to manage credentials for your applications, similar to the way that Amazon EC2 instance profiles provide credentials to Amazon EC2 instances

You may have to use a recent version of the SDK, if it's implemented using a new credential provider type.
