### ISSUE TITLE
Kinesis Analytics

### ISSUE THREAD

**Issue by marcoscale98** [kdgregory/log4j-aws-appenders#195]
Does this Appender also work when used in a AWS Kinesis Data Analytics App (Managed Apache Flink App)?

**Comment by kdgregory** [comment]
@marcoscale98 

I don't think so, although I have no experience with Flink configuration. However, my experience with other AWS managed services, such as Glue, is that you have no ability to properly configure the logging system.

Looking at the [Flink docs](https://nightlies.apache.org/flink/flink-docs-release-1.18/docs/deployment/config/#jvm-and-logging-options), it seems that the default logs are stored on disk, and there's no way to provide an alternative configuration. However, it also appears that AWS can [send Flink logs to CloudWatch](https://docs.aws.amazon.com/managed-flink/latest/java/cloudwatch-logs.html). I think that's your best option.

**Comment by marcoscale98** [comment]
Thanks @kdgregory but the built-in Kinesis Analytics system that Cloudwatch uses does not allow me to fine-filter the logs using "log4j2.properties" (or so it seemed to me from some of my tests)
Thank you anyway
