### ISSUE TITLE
Outdated aws-shared repository in Maven Central

### ISSUE THREAD

**Issue by longxiangdai** [kdgregory/log4j-aws-appenders#198]
Hi Keith,
Our service uses the [aws-shared](https://central.sonatype.com/artifact/com.kdgregory.logging/aws-shared/dependents) repository that you posted on Maven Central. We've recently encountered a throttling issue caused by excessive describeLogStreams calls from the CloudWatchLogWriter. These calls happened whenever a token was retrieved for each batch log upload. Upon investigation, I've noticed that this repository is outdated, but it's still being used by [log42j-aws-appenders](https://central.sonatype.com/artifact/com.kdgregory.logging/log4j2-aws-appenders/versions). The most recent version dates back to 2020. I'm wondering if this aws-shared package is no longer being served as a dependency, or if it just hasn't been updated yet. I looked at the code in the GitHub repository and noticed that the sendBatch function has been updated, but the aws-shared folder has been removed. The CloudWatchLogWriter now resides in the logwriter folder. Please correct me if I'm wrong or share any thoughts and suggestions. Thank you!

**Comment by kdgregory** [comment]
@longxiangdai 

`aws-shared` is part of the 2.4.1 release of this library; the current version is 3.2.0, which does not request tokens (per AWS change).

Please review the examples at https://github.com/kdgregory/log4j-aws-appenders to see the current dependency specs, as they changed between version 2 and version 3.
