### ISSUE TITLE
Inquiry on AWS Firehose Support in log4j-aws-appenders

### ISSUE THREAD

**Issue by dkswnkk** [kdgregory/log4j-aws-appenders#203]
Hello,

I have been using the Guardian's kinesis-logback-appender to send logback logs to AWS Firehose. However, as this library was deprecated as of November 30, 2023, I am looking for an alternative. The recommended replacement, as per the original repository's README, is the log4j-aws-appenders library available at https://github.com/kdgregory/log4j-aws-appenders

After reviewing the documentation and the code, it appears that this new library supports logging to Kinesis but not to Firehose. Can you confirm whether AWS Firehose is supported? If not, are there any plans to include Firehose support in the future?

Thank you for your help and for maintaining such a useful resource.

**Comment by kdgregory** [comment]
@dkswnkk 

This library does not log directly to Firehose, and I have no plans to add that feature.

Instead, I recommend logging to a Kinesis stream, and then using that as the source for Firehose. IMO this provides much more flexibility, and utilizes the best features of each service Kinesis Streams to arbitrary-sized batches of records from multiple sources, and Firehose to batch records together for a destination.
