### ISSUE TITLE
Support configuring the credential from the code

### ISSUE THREAD

**Issue by ghost** [kdgregory/log4j-aws-appenders#206]
Hey @kdgregory, could you support configuring the credential from the code instead of `~/.aws/credentials`, which is easy to deploy to multiple servers.

Some code like this
```
    @Bean
    public CloudWatchLogsClient cloudWatchLogsClient() {
        AwsBasicCredentials credentials = AwsBasicCredentials.create(accessKeyId, secretAccessKey);

        return CloudWatchLogsClient.builder()
                .region(Region.US_WEST_2)
                .credentialsProvider(StaticCredentialsProvider.create(credentials))
                .build();
    }
```
Or like this,
```
<appender name="CLOUDWATCH" class="com.kdgregory.logback.aws.CloudWatchAppender">
        <accessKeyId>{accessKeyId}</logStream>
        <secretAccessKey>{secretAccessKey}</logStream>
        <region>{region}</region>
        <logGroup>logGroup</logGroup>
        <logStream>logStream-{date}</logStream>
        <layout class="ch.qos.logback.classic.PatternLayout">
            <pattern>${logPattern}</pattern>
        </layout>
    </appender>
```

**Comment by kdgregory** [comment]
Putting credentials in a configuration file is, imo, a security risk.

One alternative is a static factory method, as described [here](https://github.com/kdgregory/log4j-aws-appenders/blob/trunk/docs/client.md#application-provided-factory-method).

Another is to define the standard AWS environment variables.

But the best approach is to use the AWS-provided credentials mechanism for your deployment platform: instance profile for EC2, execution role for Lambda, task role for ECS, etc.
