### ISSUE TITLE
how to set the region for CloudWatch

### ISSUE THREAD

**Issue by ankushBoL** [kdgregory/log4j-aws-appenders#66]
I tried to set the region using:
`log4j.appender.cloudwatch.region=us-west-2`
but it generated a warning:
log4j:WARN No such property [region] in com.kdgregory.log4j.aws.CloudWatchAppender.

Can you please help with how to set the region?

**Comment by kdgregory** [comment]
@ankushBoL 

This is described [here](https://github.com/kdgregory/log4j-aws-appenders/blob/master/docs/service-client.md), and is linked from the [configuration documentation](https://github.com/kdgregory/log4j-aws-appenders/blob/master/docs/cloudwatch.md#configuration) for the CloudWatch appender.
