### ISSUE TITLE
clientEndpoint property not found

### ISSUE THREAD

**Issue by ankushBoL** [kdgregory/log4j-aws-appenders#70]
I set the following property in the log4j properties.
`log4j.appender.cloudwatch.clientEndpoint=logs.us-west-2.amazonaws.com`
and I get the following warning
`log4j:WARN No such property [clientEndpoint] in com.kdgregory.log4j.aws.CloudWatchAppender.`

Can you please help?

**Comment by kdgregory** [comment]
@ankushBoL - please attach the complete log4j configuration. I don't see anything wrong with what you've pasted, but there's a [unit test configuration](https://github.com/kdgregory/log4j-aws-appenders/blob/master/log4j1-appenders/src/test/resources/TestCloudWatchAppender/testConfiguration.properties) that sets that value, so I have a fairly strong belief that it works.

**Comment by kdgregory** [comment]
@ankushBoL - also, which version of the library are you using? The endpoint configuration didn't get added until version 1.2.1.

**Comment by kdgregory** [comment]
I've verified that this works, using the Log4J example program and the following configuration:

```
log4j.rootLogger=WARN, console, cloudwatch

log4j.logger.com.kdgregory.log4j.aws.example=DEBUG

log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern=%d [%t] %-5p %c %x - %m%n

log4j.appender.cloudwatch=com.kdgregory.log4j.aws.CloudWatchAppender
log4j.appender.cloudwatch.logGroup=AppenderExample
log4j.appender.cloudwatch.logStream=Example-{date}-{hostname}-{pid}
log4j.appender.cloudwatch.clientEndpoint=logs.us-west-2.amazonaws.com
log4j.appender.cloudwatch.layout=org.apache.log4j.PatternLayout
log4j.appender.cloudwatch.layout.ConversionPattern=%d [%t] %-5p %c %x - %m%n
```

Note that it requires using an older SDK (one that doesn't support the client factory). However, that wouldn't result in the warning shown above. I've also created #74 to make this usable with SDK versions that do use the client factories.
