### ISSUE TITLE
Support for Log4j2

### ISSUE THREAD

**Issue by ankushBoL** [kdgregory/log4j-aws-appenders#84]
Thanks for a great library!
We are planning to move to log4j2 and couldnt fine a good cloudwatch appender.
Do you have a version that supports log4j2 and if not which one do you recommend.

**Comment by kdgregory** [comment]
@ankushBoL 

Glad you like it. Log4J2 support is on the horizon, but I have some other projects that I want to complete first. I will probably have it by June.

Unfortunately, I don't use Log4J2 myself, so can't recommend any other appenders library.
