### ISSUE TITLE
Add layout.ConversionPattern  for kinesis log4j appender

### ISSUE THREAD

**Issue by rohitaila** [kdgregory/log4j-aws-appenders#86]
I am trying to add a timestamp and application name to all of my log messages and write them to kinesis streams. But there seems to be no such option in kinesis appender source code.

**Comment by kdgregory** [comment]
@rohitaila - to use a conversion pattern, you need to use a layout manager such as the standard `PatternLayout`. The examples use such a layout for CloudWatch and SNS.

However, I strongly recommend sticking with JSON for Kinesis, as well as for CloudWatch, because it provides far more flexibility.
