### ISSUE TITLE
Cloudwatch - Ability to configure the log group retention policy from config

### ISSUE THREAD

**Issue by jibs44** [kdgregory/log4j-aws-appenders#87]

**Comment by kdgregory** [comment]
This seems reasonable, given the ability to auto-create groups/streams. Makes me wonder whether I should also add ability to configure things like KMS keys, and where the line ought to be between "you should preconfigure this" and "the logging framework can do it for you."

**Comment by jibs44** [comment]
Yeah I guess it would come down to what can you default/preconfigure in CW vs what you need to set up for each log group/stream.

**Comment by kdgregory** [comment]
This has been released as version 2.2.1, and should appear on Maven Central within a few hours.

**Comment by jibs44** [comment]
Thanks @kdgregory
