### ISSUE TITLE
CloudWatchLogWriter: DescribeLogStreams throttling

### ISSUE THREAD

**Issue by MicheledG** [kdgregory/log4j-aws-appenders#89]
Hi, I was using this library to log data produced by a clusterized application.

I've set the **batch-delay** property (CWAppender) considering throttling problems related to CloudWatchLogs [service](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html#targetText=20%2C000%20log%20groups%20per%20account,belong%20to%20one%20log%20group.) and reading your tips for design but I'm still facing exceptions caused by **DescribeLogStreams** api call.

I've seen that this call is executed every time a new **attemptToSend** invocation is executed.

https://github.com/kdgregory/log4j-aws-appenders/blob/12befdc40822c08abe7401e42341bf34c965017d/aws-shared/src/main/java/com/kdgregory/logging/aws/cloudwatch/CloudWatchLogWriter.java#L158

Since the limits for DescribeLogStreams are very low _5TPS/Account/Region_, is there any way to avoid it? Am I missing something about the configuration of the appender in order to reduce DescribeLogStreams invocations?

Thank you!

**Comment by kdgregory** [comment]
@MicheledG - Short-term, you can request a limit increase from AWS. That may not be enough, depending on the size of your cluster.

Longer-term (as in, within a week or so), I'll add a flag to the appender that tells it that it can retain the sequence number from the previous `PutLogEvents`. This will require a dedicated stream for each appender, but that seems to be the common practice anyway (as exampled by Lambda or Batch).

**Comment by MicheledG** [comment]
Thank you for the suggestions!

**Comment by kdgregory** [comment]
Should have this out by the end of this week, early next. If you'd like to follow along: https://github.com/kdgregory/log4j-aws-appenders/tree/dev-cloudwatch_dedicated_stream 

FYI: I ran some experiments this morning, and it appears that throttling uses the "bucket and refill" approach, in which there's an initial large bucket of requests and it's refilled at the throttling rate (that's pretty common with AWS services). It took me a few hundred calls (running on multiple threads) before I saw the first exception, and even then I think most were handled internally.

**Comment by MicheledG** [comment]
Just to add some context: I've faced the throttling exception while executing an Apache Flink cluster hosted on Kinesis Analytics. In my case the cluster was set with a parallelism of 64 and each writer thread was set to use a dedicated log stream.

**Comment by kdgregory** [comment]
@MicheledG - yep, that makes sense. The bucket would be emptied pretty quickly in that case.

I've finished the basic implementation. If you're OK with building it yourself, then check out the `dev-cloudwatch_dedicated_stream` branch and run `mvn clean install` from the top level. You'll then need to build your project with version `2.2.2-SNAPSHOT`.

You can see an example of the configuration change for Log4J [here](https://github.com/kdgregory/log4j-aws-appenders/blob/dev-cloudwatch_dedicated_stream/log4j1-appenders/src/test/resources/TestCloudWatchAppender/testConfiguration.properties#L12), or [here](https://github.com/kdgregory/log4j-aws-appenders/blob/dev-cloudwatch_dedicated_stream/logback-appenders/src/test/resources/TestCloudWatchAppender/testConfiguration.xml#L9) for logback.

I still need to write integration tests before releasing, but expect to be done by the end of this week if you prefer to wait.

**Comment by MicheledG** [comment]
Cool! I'll try to install and test your updated library in the next days. Thank you very much!

**Comment by kdgregory** [comment]
@MicheledG - don't use it yet -- after implementing the integration test I realized that the initial stream discovery process has to handle retries.

**Comment by kdgregory** [comment]
@MicheledG - version 2.2.2 is not available on Maven Central.

I manually tested with 25 processes that were writing every 500 millis. Without the new flag they would occasionally get a throttling error, with the new flag they ran for an hour without any errors.
