### ISSUE TITLE
Support for Log4J 2.x

### ISSUE THREAD

**Issue by sne11ius** [kdgregory/log4j-aws-appenders#92]
As stated in the readmy: "...and a future version will support Log4J 2.x".
Is there any eta for this?

**Comment by kdgregory** [comment]
@sne11ius - I'm now shooting for early 2020, but it's definitely an incentive to know that people want it.

**Comment by sne11ius** [comment]
Good to know. And thanks for making this in the first place :)

**Comment by kdgregory** [comment]
@sne11ius - this has now been released and is available on Maven Central.

But, to be honest, after spending the last two months deep in the code of Log4J2, I'm sticking with Logback for my applications.
